# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-09-03 07:12
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blog',
            options={'ordering': ['-public_time'], 'verbose_name': '\u535a\u6587', 'verbose_name_plural': '\u535a\u6587'},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': '\u6587\u7ae0\u5206\u7c7b', 'verbose_name_plural': '\u6587\u7ae0\u5206\u7c7b'},
        ),
        migrations.AlterField(
            model_name='blog',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='\u4f5c\u8005'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.Category', verbose_name='\u5206\u7c7b'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='content',
            field=models.TextField(verbose_name='\u5185\u5bb9'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='public_time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='\u53d1\u5e03\u65f6\u95f4'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='title',
            field=models.CharField(max_length=100, verbose_name='\u6807\u9898'),
        ),
        migrations.AlterField(
            model_name='category',
            name='description',
            field=models.CharField(default='', max_length=100, verbose_name='\u63cf\u8ff0'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=20, verbose_name='\u7c7b\u540d'),
        ),
    ]
