# Generated by Django 2.0.1 on 2018-01-22 03:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='article',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='blog.Blog', verbose_name='博客'),
            preserve_default=False,
        ),
    ]
