# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-10-03 00:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20170903_1512'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(max_length=20, verbose_name='\u6635\u79f0')),
                ('email', models.EmailField(max_length=254, verbose_name='\u90ae\u7bb1')),
                ('content', models.TextField(max_length=500, verbose_name='\u5185\u5bb9')),
                ('time', models.DateTimeField(auto_now_add=True, verbose_name='\u65f6\u95f4')),
            ],
            options={
                'ordering': ['-time'],
                'verbose_name': '\u8bc4\u8bba',
                'verbose_name_plural': '\u8bc4\u8bba',
            },
        ),
    ]
